<?php

/**
 * ReleaseMgt plugin
 *
 *
 * Created: 2008-01-05
 * Last update: 2008-01-09
 *
 * @link http://deboutv.free.fr/mantis/
 * @copyright 
 * @author Vincent DEBOUT <deboutv@free.fr>
 */

define( 'PLUGINS_RELEASEMGT_UPLOAD_THRESHOLD_LEVEL_DEFAULT', ADMINISTRATOR );
define( 'PLUGINS_RELEASEMGT_UPLOAD_METHOD_DEFAULT', DISK );
define( 'PLUGINS_RELEASEMGT_DISK_PATH_DEFAULT', '' );
define( 'PLUGINS_RELEASEMGT_FTP_SERVER_DEFAULT', '' );
define( 'PLUGINS_RELEASEMGT_FTP_USER_DEFAULT', '' );
define( 'PLUGINS_RELEASEMGT_FTP_PASS_DEFAULT', '' );
define( 'PLUGINS_RELEASEMGT_NOTIFICATION_ENABLE_DEFAULT', OFF );
define( 'PLUGINS_RELEASEMGT_NOTIFY_HANDLER_DEFAULT', ON );
define( 'PLUGINS_RELEASEMGT_NOTIFY_REPORTER_DEFAULT', OFF );
define( 'PLUGINS_RELEASEMGT_NOTIFY_EMAIL_DEFAULT', '' );
define( 'PLUGINS_RELEASEMGT_EMAIL_TEMPLATE_DEFAULT', 'default' );

?>